# Generated by Django 4.2.6 on 2023-10-24 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicity', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicity',
            old_name='image',
            new_name='url',
        ),
    ]
