# Generated by Django 4.2.6 on 2023-10-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicity', '0002_rename_image_publicity_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicity',
            name='url',
            field=models.ImageField(upload_to='publicity/', verbose_name='Image'),
        ),
    ]
