# Generated by Django 4.2.6 on 2023-10-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicity', '0003_alter_publicity_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicity',
            name='url',
            field=models.ImageField(upload_to='media/publicity', verbose_name='Image'),
        ),
    ]
