# Generated by Django 4.2.6 on 2023-10-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_categorie_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='', verbose_name='Images')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='images_related',
            field=models.ManyToManyField(to='post.images'),
        ),
    ]
