# Generated by Django 4.2.6 on 2023-10-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_images_images_alter_post_images_related'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='principal_image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Principal Image'),
        ),
    ]
