# Generated by Django 4.2.6 on 2023-10-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_rename_images_images_name_alter_post_principal_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='name',
            field=models.ImageField(upload_to='media/multi_images', verbose_name='Images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='principal_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/principal_images', verbose_name='Principal Image'),
        ),
    ]
